<div style="text-align: center; background-color: #b1d1ff; font-family: 'Trebuchet MS', Arial, sans-serif; color: white; padding: 20px; font-size: 56px; font-weight: bold; border-radius: 0 0 0 0; box-shadow: 0px 6px 8px rgba(0, 0, 0, 0.2);">Tiền xử lý dữ liệu</div>

# **A. Thu thập dữ liệu**

# **Dữ liệu thời tiết tại Việt Nam (2009–2021)**

## **Tổng quan về dữ liệu**
Bộ dữ liệu này ghi lại thông tin thời tiết hàng ngày tại **40 tỉnh/thành phố** ở Việt Nam trong khoảng thời gian từ **1/1/2009** đến **18/6/2021**. Dữ liệu bao gồm nhiều biến quan trọng liên quan đến nhiệt độ, tốc độ gió, lượng mưa, độ ẩm và các yếu tố thời tiết khác, giúp cung cấp cái nhìn tổng quan về tình hình khí hậu tại các địa phương.

### **Các tỉnh/thành phố được ghi nhận
- **Mi BHà Nội, Hải Phòng, Thái Nguyên, Yên Bái, Hòa Bình, Nam Định, Việt Trì, Uông Bí, Cẩm Phả, Hòn Gai, Hải Dương.n G.
- **MiềTrHuế, Đà Lạt, Tam Kỳ, Tuy Hòa, Phan Rang, Phan Thiết, Nha Trang, Cam Ranh, Vinh, Thanh Hóa, Quy Nhơn, Pleiku, Buôn Ma Thuột.y Nn.
- **ềnTP. HCM, Biên Hòa, Cần Thơ, Bạc Liêu, Cà Mau, Long Xuyên, Bến Tre, Sóc Trăng, Mỹ Tho, Rạch Giá, Tân An, Vũng Tàu, Trà Vinh, Châu Đốc, Vĩnh Long.   |

---

## **Thông tin nổi bật**
- **Thời gian**: 12 năm dữ liệu thời tiết hàng ngày (2009–2021).
- **Địa điểm**: Bao gồm 40 tỉnh/thành phố đại diện cho các vùng khí hậu khác nhau tại Việt Nam.
- **Ứng dụng**:
  - Phân tích các xu hướng thời tiết theo năm hoặc mùa.
  - Đánh giá tác động của biến đổi khí hậu.
  - Lập kế hoạch nông nghiệp và quản lý thiên tai.

Bộ dữ liệu này là nguồn tài nguyên phong phú để phân tích, dự báo thời tiết và xây dựng các dự án tực quan hóa dữ liệu.

### **Thư viện**

*Khai báo các thư viện sử dụng trong notebook*

In [1]:
import numpy as np
import pandas as pd
import re

### **Dữ liệu**

*Đọc file dữ liệu*

In [2]:
file_path = "weather.csv"
df = pd.read_csv(file_path)

*Nhìn 5 dòng đầu tiên của dữ liệu để có cái nhìn tổng quan nhất*

In [3]:
df.head()

   province  max  min  wind wind_d  rain  humidi  cloud  pressure        date
0  Bac Lieu   27   22    17    NNE   6.9      90     71      1010  2009-01-01
1  Bac Lieu   31   25    20    ENE   0.0      64     24      1010  2010-01-01
2  Bac Lieu   29   24    14      E   0.0      75     45      1008  2011-01-01
3  Bac Lieu   30   24    30      E   0.0      79     52      1012  2012-01-01
4  Bac Lieu   31   25    20    ENE   0.0      70     24      1010  2013-01-01

# **B. Xử lý dữ liệu**

### **Dữ liệu có bao nhiêu cột và dòng?**

In [4]:
shape = None
shape = df.shape
print("- Số dòng:", shape[0])
print("- Số cột:", shape[1])

if shape[0] > 1000:
    print(f"- Dữ liệu tốt.")
else:
    print(f"- Dữ liệu chưa tốt.")

- Số dòng: 181960
- Số cột: 10
- Dữ liệu tốt.

## **Ý nghĩa các cột dữ liệu**

| **Tên cột**         | **Mô tả**                                                                                  |
|----------------------|--------------------------------------------------------------------------------------------|
| **province**         | Tên tỉnh hoặc thành phố nơi dữ liệu thời tiết được ghi nhận.                              |
| **max**              | Nhiệt độ cao nhất (°C) được ghi nhận trong ngày.                                          |
| **min**              | Nhiệt độ thấp nhất (°C) được ghi nhận trong ngày.                                         |
| **wind**             | Tốc độ gió (km/h) trung bình trong ngày.                                                  |
| **wind_d**           | Hướng gió theo ký hiệu la bàn (VD: N, NNE, NE). Chi tiết xem [bảng hướng gió](#huong-gio). |
| **rain**             | Lượng mưa (mm) ghi nhận trong ngày.                                                       |
| **humidi**           | Độ ẩm trung bình (%) trong ngày.                                                          |
| **cloud**            | Mức độ mây che phủ trung bình (%) trong ngày.                                             |
| **pressure**         | Áp suất khí quyển trung bình trong ngày (hPa).                                            |
| **date**             | Ngày ghi nhận dữ liệu, định dạng `YYYY-MM-DD`.                                            |

---

## **Bảng hướng gió**

| **Hướng gió**            | **Ký hiệu** | **Góc** | **Từ góc** | **Đến góc** |
|---------------------------|-------------|---------|------------|-------------|
| **Bắc**                  | N           | 0°      | 348.75°    | 11.25°      |
| **Bắc Đông Bắc**          | NNE         | 22.5°   | 11.25°     | 33.75°      |
| **Đông Bắc**              | NE          | 45°     | 33.75°     | 56.25°      |
| **Đông Đông Bắc**         | ENE         | 67.5°   | 56.25°     | 78.75°      |
| **Đông**                 | E           | 90°     | 78.75°     | 101.25°     |
| **Đông Đông Nam**         | ESE         | 112.5°  | 101.25°    | 123.75°     |
| **Đông Nam**              | SE          | 135°    | 123.75°    | 146.25°     |
| **Nam Đông Nam**          | SSE         | 157.5°  | 146.25°    | 168.75°     |
| **Nam**                  | S           | 180°    | 168.75°    | 191.25°     |
| **Nam Tây Nam**           | SSW         | 202.5°  | 191.25°    | 213.75°     |
| **Tây Nam**               | SW          | 225°    | 213.75°    | 236.25°     |
| **Tây Tây Nam**           | WSW         | 247.5°  | 236.25°    | 258.75°     |
| **Tây**                  | W           | 270°    | 258.75°    | 281.25°     |
| **Tây Tây Bắc**           | WNW         | 292.5°  | 281.25°    | 303.75°     |
| **Tây Bắc**               | NW          | 315°    | 303.75°    | 326.25°     |
| **Bắc Tây Bắc**           | NNW         | 337.5°  | 326.25°    | 348.75°     |

---

### **Kiểm tra và chuẩn hóa dữ liệu chuỗi**

### **Dữ liệu có bị trùng lặp không?**

In [5]:
num_duplicated_rows = None
# Kiểm tra các dòng trùng lặp
num_duplicated_rows = df.duplicated().sum()

if num_duplicated_rows == 0:
    print(f"- Dữ liệu không có dòng trùng lặp.")
else:
    print(f"- Dữ liệu có {num_duplicated_rows} dòng trùng lặp.")

- Dữ liệu không có dòng trùng lặp.

### **Có bao nhiêu giá trị bị thiếu?**

*Chúng ta cần kiểm tra dữ liệu trong các cột của tập dữ liệu.*

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181960 entries, 0 to 181959
Data columns (total 10 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   province  181960 non-null  object
 1   max       181960 non-null  int64
 2   min       181960 non-null  int64
 3   wind      181960 non-null  int64
 4   wind_d    181960 non-null  object
 5   rain      181960 non-null  float64
 6   humidi    181960 non-null  int64
 7   cloud     181960 non-null  int64
 8   pressure  181960 non-null  int64
 9   date      181960 non-null  object
dtypes: float64(1), int64(6), object(3)
memory usage: 13.9+ MB

### **Các cột có kiểu dữ liệu gì?**

In [7]:
df.dtypes

province     object
max           int64
min           int64
wind          int64
wind_d       object
rain        float64
humidi        int64
cloud         int64
pressure      int64
date         object
dtype: object

In [8]:
# Kiểm tra kiểu dữ liệu trong cột 'date'
unique_formats = df['date'].apply(type).unique()
print(f"Các kiểu dữ liệu duy nhất trong cột 'date': {unique_formats}")

# Kiểm tra số lượng giá trị duy nhất và giá trị trùng lặp
unique_dates = df['date'].nunique()
total_duplicates = df.shape[0] - unique_dates
print(f"Số lượng giá trị ngày duy nhất: {unique_dates}")
print(f"Số lượng bản ghi trùng lặp dựa trên cột 'date': {total_duplicates}")

# Chuyển đổi cột 'date' sang kiểu datetime và kiểm tra khoảng thời gian
df['date_converted'] = pd.to_datetime(df['date'], errors='coerce')
date_min = df['date_converted'].min()
date_max = df['date_converted'].max()
print(f"Khoảng thời gian trong dữ liệu: Từ {date_min} đến {date_max}")

# Đếm số lượng ngày không hợp lệ
invalid_dates = df['date_converted'].isnull().sum()
print(f"Số lượng giá trị ngày không hợp lệ: {invalid_dates}")

# Thêm cột 'year' và 'month' để phân tích theo năm và tháng
df['year'] = df['date_converted'].dt.year
df['month'] = df['date_converted'].dt.month

# Phân tích dữ liệu theo năm
yearly_counts = df['year'].value_counts().sort_index()
print("Số lượng bản ghi theo từng năm:")
print(yearly_counts)

# Phân tích dữ liệu theo tháng (không phân biệt năm)
monthly_counts = df['month'].value_counts().sort_index()
print("Số lượng bản ghi theo từng tháng (không phân biệt năm):")
print(monthly_counts)

Các kiểu dữ liệu duy nhất trong cột 'date': [<class 'str'>]
Số lượng giá trị ngày duy nhất: 4549
Số lượng bản ghi trùng lặp dựa trên cột 'date': 177411
Khoảng thời gian trong dữ liệu: Từ 2009-01-01 00:00:00 đến 2021-06-18 00:00:00
Số lượng giá trị ngày không hợp lệ: 0
Số lượng bản ghi theo từng năm:
year
2009    14600
2010    14600
2011    14600
2012    14600
2013    14600
2014    14600
2015    14600
2016    14600
2017    14600
2018    14600
2019    14600
2020    14600
2021     6760
Name: count, dtype: int64
Số lượng bản ghi theo từng tháng (không phân biệt năm):
month
1     16120
2     14560
3     16120
4     15600
5     16120
6     15120
7     14880
8     14880
9     14400
10    14880
11    14400
12    14880
Name: count, dtype: int64

In [9]:
# Kiểm tra các giá trị bất thường trong cột 'rain'
invalid_rain = df[df['rain'] < 0]
print(f"Số giá trị bất thường trong cột 'rain': {len(invalid_rain)}")

# Loại bỏ các giá trị bất thường
df = df[df['rain'] >= 0]

Số giá trị bất thường trong cột 'rain': 0

In [10]:
# Kiểm tra các giá trị duy nhất trong cột 'province' và 'wind_d'
print("Danh sách các tỉnh:", df['province'].unique())
print("Danh sách hướng gió:", df['wind_d'].unique())

# Chuẩn hóa (viết thường và loại bỏ khoảng trắng)
df['province'] = df['province'].str.strip().str.title()
df['wind_d'] = df['wind_d'].str.strip().str.upper()

# Kiểm tra lại sau chuẩn hóa
print("Danh sách các tỉnh sau chuẩn hóa:", df['province'].unique())

Danh sách các tỉnh: ['Bac Lieu' 'Ho Chi Minh City' 'Tam Ky' 'Ben Tre' 'Hoa Binh' 'Tan An'
 'Bien Hoa' 'Hong Gai' 'Thai Nguyen' 'Buon Me Thuot' 'Hue' 'Thanh Hoa'
 'Ca Mau' 'Long Xuyen' 'Tra Vinh' 'Cam Pha' 'My Tho' 'Tuy Hoa' 'Cam Ranh'
 'Nam Dinh' 'Uong Bi' 'Can Tho' 'Nha Trang' 'Viet Tri' 'Chau Doc'
 'Phan Rang' 'Vinh' 'Da Lat' 'Phan Thiet' 'Vinh Long' 'Ha Noi' 'Play Cu'
 'Vung Tau' 'Hai Duong' 'Qui Nhon' 'Yen Bai' 'Hai Phong' 'Rach Gia'
 'Hanoi' 'Soc Trang']
Danh sách hướng gió: ['NNE' 'ENE' 'E' 'WSW' 'SSE' 'NE' 'SE' 'ESE' 'SW' 'NNW' 'SSW' 'S' 'W'
 'WNW' 'NW' 'N']
Danh sách các tỉnh sau chuẩn hóa: ['Bac Lieu' 'Ho Chi Minh City' 'Tam Ky' 'Ben Tre' 'Hoa Binh' 'Tan An'
 'Bien Hoa' 'Hong Gai' 'Thai Nguyen' 'Buon Me Thuot' 'Hue' 'Thanh Hoa'
 'Ca Mau' 'Long Xuyen' 'Tra Vinh' 'Cam Pha' 'My Tho' 'Tuy Hoa' 'Cam Ranh'
 'Nam Dinh' 'Uong Bi' 'Can Tho' 'Nha Trang' 'Viet Tri' 'Chau Doc'
 'Phan Rang' 'Vinh' 'Da Lat' 'Phan Thiet' 'Vinh Long' 'Ha Noi' 'Play Cu'
 'Vung Tau' 'Hai Duong' 'Qui Nhon' 'Yen Bai' 'Hai Phong' 'Rach Gia'
 'Hanoi' 'Soc Trang']

In [11]:
# Hàm phát hiện và xử lý giá trị ngoại lai dựa trên khoảng hợp lý
def remove_outliers_with_context(df, column, min_val, max_val):
    # In khoảng giá trị hợp lý
    print(f"Xử lý cột: {column}")
    print(f" - Khoảng giá trị hợp lý: [{min_val}, {max_val}]")

    # Lưu lại các giá trị ngoại lai
    outliers = df[(df[column] < min_val) | (df[column] > max_val)]
    print(f" - Số lượng outliers: {len(outliers)}")
    print(f" - Giá trị outliers:\n{outliers[column].tolist()}\n")
    
    # Loại bỏ outliers và trả kết quả
    return df[(df[column] >= min_val) & (df[column] <= max_val)]

# Áp dụng xử lý cho từng cột với khoảng giá trị hợp lý
column_ranges = {
    'max': (5, 50),
    'min': (0, 40),
    'wind': (0, 150),
    'rain': (0, 500),
    'humidi': (10, 100),
    'pressure': (980, 1050)
}

# Lặp qua từng cột số và xử lý
for col, (min_val, max_val) in column_ranges.items():
    print(f"Trước xử lý, số dòng: {len(df)}")
    df = remove_outliers_with_context(df, col, min_val, max_val)
    print(f"Sau xử lý, số dòng: {len(df)}\n")

df['is_outlier'] = ((df['max'] < 5) | (df['max'] > 50)).astype(int)

# Xem lại dữ liệu sau xử lý
df

Trước xử lý, số dòng: 181960
Xử lý cột: max
 - Khoảng giá trị hợp lý: [5, 50]
 - Số lượng outliers: 1
 - Giá trị outliers:
[4]

Sau xử lý, số dòng: 181959

Trước xử lý, số dòng: 181959
Xử lý cột: min
 - Khoảng giá trị hợp lý: [0, 40]
 - Số lượng outliers: 0
 - Giá trị outliers:
[]

Sau xử lý, số dòng: 181959

Trước xử lý, số dòng: 181959
Xử lý cột: wind
 - Khoảng giá trị hợp lý: [0, 150]
 - Số lượng outliers: 0
 - Giá trị outliers:
[]

Sau xử lý, số dòng: 181959

Trước xử lý, số dòng: 181959
Xử lý cột: rain
 - Khoảng giá trị hợp lý: [0, 500]
 - Số lượng outliers: 3
 - Giá trị outliers:
[524.5, 596.4, 596.4]

Sau xử lý, số dòng: 181956

Trước xử lý, số dòng: 181956
Xử lý cột: humidi
 - Khoảng giá trị hợp lý: [10, 100]
 - Số lượng outliers: 0
 - Giá trị outliers:
[]

Sau xử lý, số dòng: 181956

Trước xử lý, số dòng: 181956
Xử lý cột: pressure
 - Khoảng giá trị hợp lý: [980, 1050]
 - Số lượng outliers: 0
 - Giá trị outliers:
[]

Sau xử lý, số dòng: 181956

,province,max,min,wind,wind_d,rain,humidi,cloud,pressure,date,date_converted,year,month,is_outlier
0,Bac Lieu,27,22,17,NNE,6.9,90,71,1010,2009-01-01,2009-01-01,2009,1,0
1,Bac Lieu,31,25,20,ENE,0.0,64,24,1010,2010-01-01,2010-01-01,2010,1,0
2,Bac Lieu,29,24,14,E,0.0,75,45,1008,2011-01-01,2011-01-01,2011,1,0
3,Bac Lieu,30,24,30,E,0.0,79,52,1012,2012-01-01,2012-01-01,2012,1,0
4,Bac Lieu,31,25,20,ENE,0.0,70,24,1010,2013-01-01,2013-01-01,2013,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181955,Soc Trang,28,23,8,SSW,0.0,75,50,1011,2016-12-28,2016-12-28,2016,12,0
181956,Soc Trang,30,24,21,ENE,7.2,81,50,1011,2017-12-28,2017-12-28,2017,12,0
181957,Soc Trang,26,24,9,ENE,1.3,91,75,1009,2018-12-28,2018-12-28,2018,12,0
181958,Soc Trang,30,23,11,E,0.0,74,6,1012,2019-12-28,2019-12-28,2019,12,0
181959,Soc Trang,29,24,9,ESE,0.7,84,43,1009,2020-12-28,2020-12-28,2020,12,0

In [12]:
# Kiểm tra xem hai cột có giống nhau không
are_columns_equal = (df['date'] == df['date_converted']).all()
print(f"Hai cột date và date_converted có giống nhau không? {are_columns_equal}")

# Nếu giống nhau, xóa cột thừa
if are_columns_equal:
    df = df.drop(columns=['date_converted'])
    print("Đã xóa cột date_converted vì trùng với date.")

df

Hai cột date và date_converted có giống nhau không? True
Đã xóa cột date_converted vì trùng với date.

,province,max,min,wind,wind_d,rain,humidi,cloud,pressure,date,year,month,is_outlier
0,Bac Lieu,27,22,17,NNE,6.9,90,71,1010,2009-01-01,2009,1,0
1,Bac Lieu,31,25,20,ENE,0.0,64,24,1010,2010-01-01,2010,1,0
2,Bac Lieu,29,24,14,E,0.0,75,45,1008,2011-01-01,2011,1,0
3,Bac Lieu,30,24,30,E,0.0,79,52,1012,2012-01-01,2012,1,0
4,Bac Lieu,31,25,20,ENE,0.0,70,24,1010,2013-01-01,2013,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
181955,Soc Trang,28,23,8,SSW,0.0,75,50,1011,2016-12-28,2016,12,0
181956,Soc Trang,30,24,21,ENE,7.2,81,50,1011,2017-12-28,2017,12,0
181957,Soc Trang,26,24,9,ENE,1.3,91,75,1009,2018-12-28,2018,12,0
181958,Soc Trang,30,23,11,E,0.0,74,6,1012,2019-12-28,2019,12,0
181959,Soc Trang,29,24,9,ESE,0.7,84,43,1009,2020-12-28,2020,12,0

In [13]:
# Chuẩn hóa tên tỉnh/thành phố
def normalize_province_names(df, column):
    # Tạo từ điển chuẩn hóa tên
    name_mapping = {
        'Ha Noi': 'Ha Noi',
        'Hanoi': 'Ha Noi'
    }
    df[column] = df[column].replace(name_mapping)
    return df

# Áp dụng chuẩn hóa
df = normalize_province_names(df, 'province')

# Kiểm tra các tên tỉnh/thành phố
unique_provinces = df['province'].unique()
print(f"Các tỉnh/thành phố sau khi chuẩn hóa: {unique_provinces}")

Các tỉnh/thành phố sau khi chuẩn hóa: ['Bac Lieu' 'Ho Chi Minh City' 'Tam Ky' 'Ben Tre' 'Hoa Binh' 'Tan An'
 'Bien Hoa' 'Hong Gai' 'Thai Nguyen' 'Buon Me Thuot' 'Hue' 'Thanh Hoa'
 'Ca Mau' 'Long Xuyen' 'Tra Vinh' 'Cam Pha' 'My Tho' 'Tuy Hoa' 'Cam Ranh'
 'Nam Dinh' 'Uong Bi' 'Can Tho' 'Nha Trang' 'Viet Tri' 'Chau Doc'
 'Phan Rang' 'Vinh' 'Da Lat' 'Phan Thiet' 'Vinh Long' 'Ha Noi' 'Play Cu'
 'Vung Tau' 'Hai Duong' 'Qui Nhon' 'Yen Bai' 'Hai Phong' 'Rach Gia'
 'Soc Trang']

## **Lưu dữ liệu đã được làm sạch**

Cuối cùng, chúng ta sẽ lưu dữ liệu đã được tiền xử lí (làm sạch, xử lí ngoại lệ) vào một file .csv có tên là cleaned_data_Data_Scientist_Salary để thuận lợi cho các việc phân tích sau này.

In [14]:
output_path = 'cleaned_weather_output.csv'
df.to_csv(output_path, index=False)
print(f"Dữ liệu đã được lưu tại {output_path}")

Dữ liệu đã được lưu tại cleaned_weather_output.csv

In [15]:
# Đọc file cleaned_weather.csv
data = pd.read_csv('cleaned_weather_output.csv')

# Xem trước dữ liệu
print(data.head())

   province  max  min  wind wind_d  rain  humidi  cloud  pressure        date  \
0  Bac Lieu   27   22    17    NNE   6.9      90     71      1010  2009-01-01
1  Bac Lieu   31   25    20    ENE   0.0      64     24      1010  2010-01-01
2  Bac Lieu   29   24    14      E   0.0      75     45      1008  2011-01-01
3  Bac Lieu   30   24    30      E   0.0      79     52      1012  2012-01-01
4  Bac Lieu   31   25    20    ENE   0.0      70     24      1010  2013-01-01

   year  month  is_outlier
0  2009      1           0
1  2010      1           0
2  2011      1           0
3  2012      1           0
4  2013      1           0

In [16]:
# Bảng tham chiếu khu vực
# Mountain: 'Hoa Binh', 'Buon Me Thuot', 'Yen Bai', 'Play Cu', 'Da Lat', 'Uong Bi', 'Thai Nguyen'
# Plain: 'Ha Noi', 'Hanoi', 'Viet Tri', 'Tan An', 'Hai Duong', 'Can Tho', 'Bien Hoa', 'Vinh', 'Chau Doc', 'Hue', 'Long Xuyen', 'Vinh Long'
# Coastal: 'Bac Lieu', 'Ho Chi Minh City', 'Tam Ky', 'Hong Gai', 'Cam Pha', 'My Tho', 'Tuy Hoa', 'Tra Vinh', 'Ben Tre', 'Nam Dinh',
#         'Cam Ranh', 'Nha Trang', 'Phan Rang', 'Phan Thiet', 'Vung Tau', 'Hai Phong', 'Soc Trang', 'Thanh Hoa', 'Ca Mau' 'Qui Nhon', Rach Gia'

region_mapping = {
    'Hoa Binh': 'mountain',
    'Buon Me Thuot': 'mountain',
    'Yen Bai': 'mountain',
    'Play Cu': 'mountain',
    'Da Lat': 'mountain',
    'Uong Bi': 'mountain',
    'Thai Nguyen': 'mountain',
    
    'Ha Noi': 'plain',
    'Viet Tri': 'plain',
    'Tan An': 'plain',
    'Hai Duong': 'plain',
    'Can Tho': 'plain',
    'Bien Hoa': 'plain',
    'Vinh': 'plain',
    'Chau Doc': 'plain',
    'Hue': 'plain',
    'Long Xuyen': 'plain',
    'Vinh Long': 'plain',
    
    'Bac Lieu': 'coastal',
    'Ho Chi Minh City': 'coastal',
    'Tam Ky': 'coastal',
    'Hong Gai': 'coastal',
    'Cam Pha': 'coastal',
    'My Tho': 'coastal',
    'Tuy Hoa': 'coastal',
    'Tra Vinh': 'coastal',    
    'Ben Tre': 'coastal',
    'Nam Dinh': 'coastal',
    'Cam Ranh': 'coastal',
    'Nha Trang': 'coastal',
    'Phan Rang': 'coastal',
    'Phan Thiet': 'coastal',
    'Vung Tau': 'coastal',
    'Hai Phong': 'coastal',
    'Soc Trang': 'coastal',    
    'Thanh Hoa': 'coastal',
    'Ca Mau': 'coastal',
    'Qui Nhon': 'coastal',
    'Rach Gia': 'coastal'
}

# Thêm cột 'region' vào dataset
data['region'] = data['province'].map(region_mapping)

# Kiểm tra kết quả
print(data[['province', 'pressure', 'region']].head())

   province  pressure   region
0  Bac Lieu      1010  coastal
1  Bac Lieu      1010  coastal
2  Bac Lieu      1008  coastal
3  Bac Lieu      1012  coastal
4  Bac Lieu      1010  coastal

In [17]:
data.to_csv('cleaned_weather_output.csv', index=False)